### ISSUE TITLE
concordances

### ISSUE THREAD

**Issue by colemanrob** [eworx-org/labourR#7]
Hi - any chance to offer concordance functions with NOC?

great stuff!

**Comment by AleKoure** [comment]
Concordance is interesting. It should be relatively straight forward. Is there an established mapping between version ISCO-08 and NOC?

**Comment by AleKoure** [comment]
Concordances are handled in [iscoCrosswalks](https://github.com/eworx-org/iscoCrosswalks) package.
Currently supports ISCO to SOC, and vice versa.
