### ISSUE TITLE
Using custom dictionaries in labourR package

### ISSUE THREAD

**Issue by tzoltak** [eworx-org/labourR#8]
I have a feature request: it will be great if the package enabled user to supply his/her own dictionary of _names_ connected with each ISCO occupation.

This will be useful while applying package to survey data. On the one hand respondents' answers to questions regarding occupations are somewhat different from _official_ names of occupations, so specific (_survey_) dictionary may be useful to improve quality of codding. On the other hand there is a lot of data from previous research that contain human coded mapping of respndents' answers to ISCO codes, that may be used as dictionaries.

And besides I'd like to thank you for this very useful package!

**Comment by AleKoure** [comment]
Thanks for the issue! We are looking into this case. 

- Issue #2 is related to the extended mappings/dictionaries and human coded data. 

- The user might also want to use non-English names for the ISCO codes. This is also connected to the custom dictionary of names connected with each ISCO occupation.

**Comment by AleKoure** [comment]
This is similar to spellchecking.
Also, [iscoCrosswalks ](https://github.com/eworx-org/iscoCrosswalks) can help with this by retrieving the codes of the suggested occupations.
Then merging with the custom dictionary should be sufficient.
